apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
spec:
  containers:
    - name: postgres-client
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: parham
        - name: PGDATA
          value: /var/lib/postgresql/data/parham/
      volumeMounts:
        - name: postgres-volume
          mountPath: /var/lib/postgresql/data
      resources:
        limits:
          cpu: 100m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 512Mi
  volumes:
    - name: postgres-volume
      emptyDir: {}
