apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
spec:
  containers:
    - name: mysql-client
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: raha
      volumeMounts:
        - name: khar
          mountPath: /var/lib/mysql
      resources:
        limits:
          cpu: 100m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 512Mi
  volumes:
    - name: khar
      emptyDir: {}