apiVersion: v1
kind: Pod
metadata:
  name: redis-nonpersistent
spec:
  containers:
    - name: redis-nonpersistent
      image: redis
      args:
        - "--save"
        - ""
        - "--appendonly"
        - "no"
      volumeMounts:
        - name: khar
          mountPath: /data
      resources:
        limits:
          cpu: 100m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 512Mi
  volumes:
    - name: khar
      emptyDir: {}