apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app.snappcloud.io/name: sattar
        app.snappcloud.io/managed-by: seculatory
        app.snappcloud.io/created-by: ${CREATED_BY}
        app: sattar
      name: sattar-config
    data:
      config.yml: |-
        listen: ${LISTEN}
        logging:
          level: ${LOGGING_LEVEL}
        database:
          host: ${DATABASE_HOST}
          port: ${DATABASE_PORT}
          db: ${DATABASE_DB}
          user: ${DATABASE_USER}
          password: ${DATABASE_PASSWORD}
          max_conn: ${DATABASE_MAX_CONN}
          idle_conn: ${DATABASE_IDLE_CONN}
          timeout: ${DATABASE_TIMEOUT}
          dial_retry: ${DATABASE_DIAL_RETRY}
          dial_timeout: ${DATABASE_DIAL_TIMEOUT}
        base_api_database:
          host: ${BASE_API_DATABASE_HOST}
          port: ${BASE_API_DATABASE_PORT}
          db: ${BASE_API_DATABASE_DB}
          user: ${BASE_API_DATABASE_USER}
          password: ${BASE_API_DATABASE_PASSWORD}
          max_conn: ${BASE_API_DATABASE_MAX_CONN}
          idle_conn: ${BASE_API_DATABASE_IDLE_CONN}
          timeout: ${BASE_API_DATABASE_TIMEOUT}
          dial_retry: ${BASE_API_DATABASE_DIAL_RETRY}
          dial_timeout: ${BASE_API_DATABASE_DIAL_TIMEOUT}
        redis:
          address: ${REDIS_ADDRESS}
          password: ${REDIS_PASSWORD}
          db: ${REDIS_DB}
          max_conn: ${REDIS_MAX_CONN}
          idle_conn: ${REDIS_IDLE_CONN}
          read_timeout: ${REDIS_READ_TIMEOUT}
          write_timeout: ${REDIS_WRITE_TIMEOUT}
          dial_retry: ${REDIS_DIAL_RETRY}
          dial_timeout: ${REDIS_DIAL_TIMEOUT}
        providers:
          irancell:
            passenger_numbers: ${PROVIDERS_IRANCELL_PASSENGER_NUMBERS}
            driver_numbers: ${PROVIDERS_IRANCELL_DRIVER_NUMBERS}
            account_owner_numbers: ${PROVIDERS_IRANCELL_ACCOUNT_OWNER_NUMBERS}
          fanap:
            passenger_numbers: ${PROVIDERS_FANAP_PASSENGER_NUMBERS}
            driver_numbers: ${PROVIDERS_FANAP_DRIVER_NUMBERS}
            account_owner_numbers: ${PROVIDERS_FANAP_ACCOUNT_OWNER_NUMBERS}
        provider_selection: ride_id
        user_status_sync_retries: 3
        user_status_sync_buffer_size: 100
        user_status_read_from_base_api: false
        user_status_sync_delay: 15s
        ride_cache_ttl: 1h
parameters:
  - name: CREATED_BY
    description: "name of deployer"
    displayName: "created by"
    required: true
    value: "seculatory"
  - name: LISTEN
    displayName: listen
    required: true
    value: "0.0.0.0:8080"
  - name: LOGGING_LEVEL
    displayName: logging level
    required: true
    value: "debug"
  - name: DATABASE_HOST
    displayName: database host
    required: true
    value: "mysql"
  - name: DATABASE_PORT
    displayName: database port
    required: true
    value: "3306"
  - name: DATABASE_DB
    displayName: database db
    required: true
    value: "sattar"
  - name: DATABASE_USER
    displayName: database user
    required: true
    value: "root"
  - name: DATABASE_PASSWORD
    displayName: database password
    required: true
    value: "password"
  - name: DATABASE_MAX_CONN
    displayName: database max conn
    required: true
    value: "10"
  - name: DATABASE_IDLE_CONN
    displayName: database idle conn
    required: true
    value: "5"
  - name: DATABASE_TIMEOUT
    displayName: database timeout
    required: true
    value: "10s"
  - name: DATABASE_DIAL_RETRY
    displayName: database dial retry
    required: true
    value: "12"
  - name: DATABASE_DIAL_TIMEOUT
    displayName: database dial timeout
    required: true
    value: "5s"
  - name: BASE_API_DATABASE_HOST
    displayName: base api database host
    required: true
    # It should chage
    value: "mysql"
  - name: BASE_API_DATABASE_PORT
    displayName: base api database port
    required: true
    value: "3306"
  - name: BASE_API_DATABASE_DB
    displayName: base api database db
    required: true
    value: "base-api"
  - name: BASE_API_DATABASE_USER
    displayName: base api database user
    required: true
    value: "root"
  - name: BASE_API_DATABASE_PASSWORD
    displayName: base api database password
    required: true
    value: "root"
  - name: BASE_API_DATABASE_MAX_CONN
    displayName: base api database max conn
    required: true
    value: "10"
  - name: BASE_API_DATABASE_IDLE_CONN
    displayName: base api database idle conn
    required: true
    value: "5"
  - name: BASE_API_DATABASE_TIMEOUT
    displayName: base api database timeout
    required: true
    value: "10s"
  - name: BASE_API_DATABASE_DIAL_RETRY
    displayName: base api database dial retry
    required: true
    value: "12"
  - name: BASE_API_DATABASE_DIAL_TIMEOUT
    displayName: base api database dial timeout
    required: true
    value: "5s"
  - name: REDIS_ADDRESS
    displayName: redis address
    required: true
    value: "redis:6379"
  - name: REDIS_PASSWORD
    displayName: redis password
    required: true
    value: "''"
  - name: REDIS_DB
    displayName: redis db
    required: true
    value: "4"
  - name: REDIS_MAX_CONN
    displayName: redis max conn
    required: true
    value: "10"
  - name: REDIS_IDLE_CONN
    displayName: redis idle conn
    required: true
    value: "5"
  - name: REDIS_READ_TIMEOUT
    displayName: redis read timeout
    required: true
    value: "1s"
  - name: REDIS_WRITE_TIMEOUT
    displayName: redis write timeout
    required: true
    value: "1s"
  - name: REDIS_DIAL_RETRY
    displayName: redis dial retry
    required: true
    value: "12"
  - name: REDIS_DIAL_TIMEOUT
    displayName: redis dial timeout
    required: true
    value: "5s"
  - name: PROVIDERS_IRANCELL_PASSENGER_NUMBERS
    displayName: providers irancell passenger numbers
    required: true
    value: "['+989010009002']"
  - name: PROVIDERS_IRANCELL_DRIVER_NUMBERS
    displayName: providers irancell driver numbers
    required: true
    value: "['+989010009001']"
  - name: PROVIDERS_IRANCELL_ACCOUNT_OWNER_NUMBERS
    displayName: providers irancell owner numbers
    required: true
    value: "['+989010009003']"
  - name: PROVIDERS_FANAP_PASSENGER_NUMBERS
    displayName: providers fanap passenger numbers
    required: true
    value: "['+982191039002']"
  - name: PROVIDERS_FANAP_DRIVER_NUMBERS
    displayName: providers fanap driver numbers
    required: true
    value: "['+982191039001']"
  - name: PROVIDERS_FANAP_ACCOUNT_OWNER_NUMBERS
    displayName: providers fanap owner numbers
    required: true
    value: "['+982191039003']"
