apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app.snappcloud.io/name: sattar
        app.snappcloud.io/version: ${SERVICE_IMAGE_TAG}
        app.snappcloud.io/managed-by: seculatory
        app.snappcloud.io/created-by: ${CREATED_BY}
        app: sattar
      name: sattar
    spec:
      replicas: 1
      selector:
        app: sattar
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: sattar
        spec:
          initContainers:
            - name: sattar-wait-for-mysql
              image: ph4r5h4d/wait4it
              args:
                - "-type=mysql"
                - "-h=${DATABASE_HOST}"
                - "-p=${DATABASE_PORT}"
                - "-t=60"
                - "-u=${DATABASE_USER}"
                - "-P=${DATABASE_PASSWORD}"
            - name: sattar-create-db
              image: docker-registry.default.svc:5000/docker/db-clients:alpine3.11
              env:
                - name: MYSQL_PWD
                  valueFrom:
                    secretKeyRef:
                      name: mysqlcentral
                      key: database-root-password
                - name: MYSQL_TCP_PORT
                  value: '${DATABASE_PORT}'
                - name: MYSQL_HOST
                  value: '${DATABASE_HOST}'
              command: ["mysql"]
              args:
                - "-u"
                - "root"
                - "-e"
                - "CREATE DATABASE IF NOT EXISTS `${DATABASE_DB}`;"
            - name: sattar-init
              image: registry.apps.private.teh-1.snappcloud.io/mozart/sattar:${SERVICE_IMAGE_TAG}
              command: ["/app/sattar", "migrate", "-m", "/app/migrations"]
              volumeMounts:
                - name: sattar-config
                  mountPath: /app/config.yml
                  subPath: config.yml
                  readOnly: true
          containers:
            - name: sattar
              image: registry.apps.private.teh-1.snappcloud.io/mozart/sattar:${SERVICE_IMAGE_TAG}
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
              volumeMounts:
                - name: sattar-config
                  mountPath: /app/config.yml
                  subPath: config.yml
                  readOnly: true
              resources:
                limits:
                  memory: ${SATTAR_MEMORY_LIMIT}
          volumes:
            - name: sattar-config
              configMap:
                name: sattar-config
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          terminationGracePeriodSeconds: 30

parameters:
  - name: SERVICE_IMAGE_TAG
    displayName: Deployment branch
    required: true
    value: "master"
  - name: SATTAR_MEMORY_LIMIT
    displayName: POD image memory limit
    required: true
    value: "32Mi"
  - name: CREATED_BY
    description: "name of deployer"
    displayName: "created by"
    required: true
    value: "seculatory"
  - name: DATABASE_HOST
    displayName: database host
    required: true
    value: "mysql"
  - name: DATABASE_PORT
    displayName: database port
    required: true
    value: "3306"
  - name: DATABASE_DB
    displayName: database db
    required: true
    value: "sattar"
  - name: DATABASE_USER
    displayName: database user
    required: true
    value: "root"
  - name: DATABASE_PASSWORD
    displayName: database password
    required: true
    value: "password"