apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.snappcloud.io/name: sattar
        app.snappcloud.io/managed-by: seculatory
        app.snappcloud.io/created-by: ${CREATED_BY}
        app: sattar
      name: sattar
    spec:
      selector:
        app: sattar
      ports:
        - name: sattar-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      sessionAffinity: None
      type: ClusterIP

parameters:
  - name: CREATED_BY
    description: "name of deployer"
    displayName: "created by"
    required: true
    value: seculatory
